services:
  postgres:
    image: postgres:17
    container_name: refrigerai-db
    environment:
      - POSTGRES_USER=y.h.heo
      - POSTGRES_DB=refrigerai
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
